version: '3.8'

services:
  nest_boilerplate:
    container_name: nest_boilerplate
    image: nest_boilerplate:1.0.0
    build:
      context: .
      target: development
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - nest_boilerplate_mongodb
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped

  nest_boilerplate_mongodb:
    container_name: ${DATABASE_HOST}
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./.mongo-data:/data/db
    restart: unless-stopped

  nest_boilerplate_mongo_express:
    container_name: nest_boilerplate_mongo_express
    image: mongo-express:latest
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${DATABASE_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${DATABASE_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${DATABASE_URI}?authSource=admin
    ports:
      - 8002:8081
    depends_on:
      - nest_boilerplate_mongodb
    restart: unless-stopped

networks:
  default:
    driver: bridge
